# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Acme-About-TOBYINK/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Acme/About/TOBYINK.pm" .
